### ISSUE TITLE
Bug: Not supported in nonebot 2.0.0rc3

### ISSUE THREAD

**Issue by VXenomac** [nonebot/adapter-feishu#31]
nonebot2 发布了新版本https://github.com/nonebot/nonebot2/releases
对于 nonebot.drivers 下的 HTTPRequest、HTTPResponse，nonebot.adapters 下的 Bot 等都有变更
当前 adapters 无法正常运行，希望早日适配

**Comment by StarHeartHunt** [comment]
我本地测试适配器是可以正常加载使用的，能发一下你环境的报错吗？

**Comment by VXenomac** [comment]
抱歉，应该是我本机的虚拟环境串了导致调用了错误的版本，应该没有其他问题了，我先关闭了
