### ISSUE TITLE
Bug: Bot.__init__() 的参数问题

### ISSUE THREAD

**Issue by MeetWq** [nonebot/adapter-feishu#66]
**描述问题：**

由于 `Bot.__init__()` 中的参数与 Bot 基类不匹配，导致没法使用 `nonebug` 中的 `create_bot` 进行测试

Telegram 适配器有过类似的问题 https://github.com/nonebot/adapter-telegram/pull/39

**Comment by MeetWq** [comment]
另外，为什么 `Bot.type` 和 `Adapter.get_name()` 要设置成不一样的字符串？正常情况下这两者是一样的

**Comment by StarHeartHunt** [comment]
> 另外，为什么 `Bot.type` 和 `Adapter.get_name()` 要设置成不一样的字符串？正常情况下这两者是一样的

这个刚刚去看了一下应该是 a16 的时候按着 onebot(cqhttp) 适配器的写法写的，后面删掉了。等下开个 pr 修这两个问题。

**Comment by MeetWq** [comment]
暂时没发现别的问题
