### ISSUE TITLE
Bug: 在群内@机器人时，如果@放在消息末尾，会导致报错

### ISSUE THREAD

**Issue by Yisan5772156** [nonebot/adapter-feishu#81]
**描述问题：**

当在群内使用"xxxxx @Bot"时，抛出错误
future: <Task finished name='Task-68331' coro=<Bot.handle_event() done, defined at /usr/local/lib/python3.8/site-packages/nonebot/adapters/feishu/bot.py:219> exception=TypeError('string indices must be integers')>
Traceback (most recent call last):
> File "/usr/local/lib/python3.8/site-packages/nonebot/adapters/feishu/bot.py", line 222, in handle_event
    _check_nickname(self, event)
  File "/usr/local/lib/python3.8/site-packages/nonebot/adapters/feishu/bot.py", line 102, in _check_nickname
    first_text = first_msg_seg.data["text"]
TypeError: string indices must be integers

**如何复现？**

在群内发送"xxxxx @your_bot"

**期望的结果**

能够将消息接收后由插件自行解析处理这样的消息

**Comment by StarHeartHunt** [comment]
fixed in [33ba969](https://github.com/nonebot/adapter-feishu/commit/33ba969e2d7d359e70ba637bcb38947aa3aac4b8)
