### ISSUE TITLE
Bug: post 类型的消息无法匹配命令

### ISSUE THREAD

**Issue by MeetWq** [nonebot/adapter-feishu#88]
**描述问题：**

当文字和图片一起发送时，消息类型为 "post"，无法匹配开头文字中的命令

**如何复现？**

文字和图片一起发送，如 `/echo [图片]`

**期望的结果**

希望文字和图片一起发时能匹配开头的命令

**环境信息：**

 - OS: Windows
 - Python Version: 3.10
 - Nonebot Version: 2.1.2
 - nonebot-adapter-feishu Version: 2.3.1

**截图或日志**

![Snipaste_2024-01-13_16-56-10](https://github.com/nonebot/adapter-feishu/assets/33149974/f85509ce-495a-408c-83ab-38f8ead85429)
![Snipaste_2024-01-13_16-58-38](https://github.com/nonebot/adapter-feishu/assets/33149974/b037cf6b-e228-40e5-b52a-a70f6d7059e1)

相关 issue：https://github.com/noneplugin/nonebot-plugin-memes/issues/72

**Comment by StarHeartHunt** [comment]
close in fdbda70aa0132ca4083c48ea5b1a5c37079ed3b8
