### ISSUE TITLE
Bug: 无法启动

### ISSUE THREAD

**Issue by SuperGuGuGu** [nonebot/adapter-feishu#91]
### 操作系统

Windows

### Python 版本

3.11.6

### NoneBot 版本

2.1.3

### 飞书适配器版本

2.3.1

### 描述问题

安装适配器后启动报错

### 复现步骤

1.新建nb项目
2.驱动器：httpx
3.适配器：飞书
4.cd feishubot
5.nb run

### 截图或日志

![Snipaste_2024-01-19_17-34-49](https://github.com/nonebot/adapter-feishu/assets/109544213/065a0ab0-c0f9-4e2e-b6f5-d0c93d06225f)

**Comment by StarHeartHunt** [comment]
检查一下虚拟环境里是否有 nonebot1 和 nonebot2 混装

**Comment by SuperGuGuGu** [comment]
虚拟环境使用nb-cli新建的虚拟环境，不存在nonebot1

**Comment by StarHeartHunt** [comment]
> 虚拟环境使用nb-cli新建的虚拟环境，不存在nonebot1

我这边没有复现成功，上面报错里面有 CommandSession 只可能是 NoneBot 1 由于各种原因被装进来了（比如误操作或者某些插件写错依赖），你可以自己激活一下 venv，pip uninstall 掉 nb1 和 nb2 再重新装 nb2。

**Comment by SuperGuGuGu** [comment]
只装nb2后会报另一个错误。
![Snipaste_2024-01-19_23-07-07](https://github.com/nonebot/adapter-feishu/assets/109544213/3b63da46-e957-40a1-ba29-1d22747af4c3)

复现步骤：【
nb 创建项目（bootstrap httpx 飞书 立刻安装依赖 创建虚拟环境）
（现在创建貌似没有nb1）
pip uninstall nonebot
pip install nonebot2
nb run
】

**Comment by SuperGuGuGu** [comment]
![Snipaste_2024-01-19_23-25-20](https://github.com/nonebot/adapter-feishu/assets/109544213/90e75851-6084-4bd0-becb-9031929c2a52)
![Snipaste_2024-01-19_23-30-45](https://github.com/nonebot/adapter-feishu/assets/109544213/07deed72-56af-4c20-b9f0-626dae814019)

另外，飞书适配器应该使用哪个驱动器？曾经使用fastapi可以正常运行，现在使用fastapi或者httpx均不可运行

**Comment by StarHeartHunt** [comment]
> ![Snipaste_2024-01-19_23-25-20](https://private-user-images.githubusercontent.com/109544213/298113895-90e75851-6084-4bd0-becb-9031929c2a52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2Nzk1NTQsIm5iZiI6MTcwNTY3OTI1NCwicGF0aCI6Ii8xMDk1NDQyMTMvMjk4MTEzODk1LTkwZTc1ODUxLTYwODQtNGJkMC1iZWNiLTkwMzE5MjljMmE1Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQxNTQ3MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYTRkMzUzNGVhMWVhMjQ4MGYxODExMzgyNDBmODVlNzY4ODU1Zjg3ODc0OTcwNDg4Y2MyNWE3MjQ3OTBlZTU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Q7cYuThZ1Sn3hGmySfjuoGk4iihZWO8b7o3JyhB-V4U) ![Snipaste_2024-01-19_23-30-45](https://private-user-images.githubusercontent.com/109544213/298115426-07deed72-56af-4c20-b9f0-626dae814019.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2Nzk1NTQsIm5iZiI6MTcwNTY3OTI1NCwicGF0aCI6Ii8xMDk1NDQyMTMvMjk4MTE1NDI2LTA3ZGVlZDcyLTU2YWYtNGMyMC1iOWYwLTYyNmRhZTgxNDAxOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQxNTQ3MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNGIwMDQ3MjgwYWFlZGIwZGRkMTVkNzU4NjM3YTE0YjFiMzEzMDJiNzgxMDFkMzFkODVkMjk5ZGM0YWY3OTdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JgerA2ew6l9FVJDicKWsxZjS_Yg3oNn6n2__LdISda4)
> 
> 另外，飞书适配器应该使用哪个驱动器？曾经使用fastapi可以正常运行，现在使用fastapi或者httpx均不可运行

根据[适配器规范](https://github.com/nonebot/nonebot2/issues/2435)，飞书现在不再直接依赖 httpx，而是通过 nb2 提供，所以需要同时启用 fastapi 和 httpx driver

**Comment by SuperGuGuGu** [comment]
已成功启动运行
